"""Added composite pk names

Revision ID: 077f7162e845
Revises: 82517ba72f01
Create Date: 2023-11-14 12:32:36.142353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '077f7162e845'
down_revision: Union[str, None] = '82517ba72f01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_languages_id', 'languages', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_languages_id', 'languages', type_='unique')
    # ### end Alembic commands ###
