"""Viewport and Country in Places

Revision ID: 32737c666c67
Revises: 8c1506f28301
Create Date: 2023-11-23 15:47:09.646098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '32737c666c67'
down_revision: Union[str, None] = '8c1506f28301'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq__communities__id', 'communities', ['id'])
    op.add_column('places', sa.Column('country_code', sa.String(), nullable=True))
    op.add_column('places', sa.Column('country_name', sa.String(), nullable=True))
    op.add_column('places', sa.Column('viewport', geoalchemy2.types.Geometry(geometry_type='POLYGON', from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('places', 'viewport')
    op.drop_column('places', 'country_name')
    op.drop_column('places', 'country_code')
    op.drop_constraint('uq__communities__id', 'communities', type_='unique')
    # ### end Alembic commands ###
