"""User Connections

Revision ID: 71b294f43612
Revises: 390594531946
Create Date: 2023-12-23 08:45:10.980095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71b294f43612'
down_revision: Union[str, None] = '390594531946'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_connection_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', name='user_connection_request_status'), nullable=True),
    sa.Column('requester_user_id', sa.UUID(), nullable=False),
    sa.Column('requested_user_id', sa.UUID(), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['requested_user_id'], ['users.id'], name='fk__user_connection_requests.requested_user_id__users.id'),
    sa.ForeignKeyConstraint(['requester_user_id'], ['users.id'], name='fk__user_connection_requests.requester_user_id__users.id'),
    sa.PrimaryKeyConstraint('id', name='pk__user_connection_requests__id')
    )
    op.create_table('user_connections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('connected_user_id', sa.UUID(), nullable=False),
    sa.Column('connection_request_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['connected_user_id'], ['users.id'], name='fk__user_connections.connected_user_id__users.id'),
    sa.ForeignKeyConstraint(['connection_request_id'], ['user_connection_requests.id'], name='fk__user_connections.conn_req_id__user_connection_requests.id'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk__user_connections.user_id__users.id'),
    sa.PrimaryKeyConstraint('id', name='pk__user_connections__id'),
    sa.UniqueConstraint('user_id', 'connected_user_id', name='uq__user_connections__user_id__connected_user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_connections')
    op.drop_table('user_connection_requests')
    op.execute('DROP TYPE IF EXISTS user_connection_request_status;')
    # ### end Alembic commands ###
