"""Association tables sort order

Revision ID: 729b72232358
Revises: 077f7162e845
Create Date: 2023-11-15 13:22:31.843581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '729b72232358'
down_revision: Union[str, None] = '077f7162e845'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_interests', sa.Column('user_preferred_sort_order', sa.Integer(), nullable=True))
    op.add_column('user_languages', sa.Column('user_preferred_sort_order', sa.Integer(), nullable=True))
    op.add_column('user_occupations', sa.Column('user_preferred_sort_order', sa.Integer(), nullable=True))
    op.add_column('user_skills', sa.Column('user_preferred_sort_order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_skills', 'user_preferred_sort_order')
    op.drop_column('user_occupations', 'user_preferred_sort_order')
    op.drop_column('user_languages', 'user_preferred_sort_order')
    op.drop_column('user_interests', 'user_preferred_sort_order')
    # ### end Alembic commands ###
