"""User Service - Initial

Revision ID: 8e8d8b4fb1e1
Revises: 6e03479da741
Create Date: 2023-10-10 20:52:50.595255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e8d8b4fb1e1'
down_revision: Union[str, None] = '6e03479da741'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'interests', ['id'])
    op.create_unique_constraint(None, 'occupations', ['id'])
    op.create_unique_constraint(None, 'places', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'places', type_='unique')
    op.drop_constraint(None, 'occupations', type_='unique')
    op.drop_constraint(None, 'interests', type_='unique')
    # ### end Alembic commands ###
