"""Added interests, skills, occupations

Revision ID: b78871c018c6
Revises: 8e8d8b4fb1e1
Create Date: 2023-11-12 22:52:52.896478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b78871c018c6'
down_revision: Union[str, None] = '8e8d8b4fb1e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', postgresql.CITEXT(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_skills_id'),
    sa.UniqueConstraint('id', name='uq_skills_id'),
    sa.UniqueConstraint('name', name='uq_skills_name')
    )
    op.alter_column('interests', 'name',
               existing_type=sa.VARCHAR(),
               type_=postgresql.CITEXT(),
               existing_nullable=False)
    op.drop_constraint('interests_id_key', 'interests', type_='unique')
    op.create_unique_constraint('uq_interests_id', 'interests', ['id'])
    op.create_unique_constraint('uq_interests_name', 'interests', ['name'])
    op.alter_column('occupations', 'name',
               existing_type=sa.VARCHAR(),
               type_=postgresql.CITEXT(),
               existing_nullable=False)
    op.drop_constraint('occupations_id_key', 'occupations', type_='unique')
    op.create_unique_constraint('uq_occupations_id', 'occupations', ['id'])
    op.create_unique_constraint('uq_occupations_name', 'occupations', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_occupations_name', 'occupations', type_='unique')
    op.drop_constraint('uq_occupations_id', 'occupations', type_='unique')
    op.create_unique_constraint('occupations_id_key', 'occupations', ['id'])
    op.alter_column('occupations', 'name',
               existing_type=postgresql.CITEXT(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_constraint('uq_interests_name', 'interests', type_='unique')
    op.drop_constraint('uq_interests_id', 'interests', type_='unique')
    op.create_unique_constraint('interests_id_key', 'interests', ['id'])
    op.alter_column('interests', 'name',
               existing_type=postgresql.CITEXT(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_table('skills')
    # ### end Alembic commands ###
