"""Initial Migrations - Empty

Revision ID: bc616c6e5620
Revises: 
Create Date: 2023-11-16 23:36:09.640832

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = 'bc616c6e5620'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
