"""Created_by for id name models

Revision ID: d582a2e0aada
Revises: 3beb8c590a36
Create Date: 2023-11-21 16:43:25.371552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd582a2e0aada'
down_revision: Union[str, None] = '3beb8c590a36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interests', sa.Column('created_by_user_id', sa.UUID(), nullable=True))
    op.create_foreign_key('fk__interests.created_by__users.id', 'interests', 'users', ['created_by_user_id'], ['id'])
    op.add_column('languages', sa.Column('created_by_user_id', sa.UUID(), nullable=True))
    op.create_foreign_key('fk__languages.created_by__users.id', 'languages', 'users', ['created_by_user_id'], ['id'])
    op.add_column('occupations', sa.Column('created_by_user_id', sa.UUID(), nullable=True))
    op.create_foreign_key('fk__occupations.created_by__users.id', 'occupations', 'users', ['created_by_user_id'], ['id'])
    op.add_column('skills', sa.Column('created_by_user_id', sa.UUID(), nullable=True))
    op.create_foreign_key('fk__skills.created_by__users.id', 'skills', 'users', ['created_by_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk__skills.created_by__users.id', 'skills', type_='foreignkey')
    op.drop_column('skills', 'created_by_user_id')
    op.drop_constraint('fk__occupations.created_by__users.id', 'occupations', type_='foreignkey')
    op.drop_column('occupations', 'created_by_user_id')
    op.drop_constraint('fk__languages.created_by__users.id', 'languages', type_='foreignkey')
    op.drop_column('languages', 'created_by_user_id')
    op.drop_constraint('fk__interests.created_by__users.id', 'interests', type_='foreignkey')
    op.drop_column('interests', 'created_by_user_id')
    # ### end Alembic commands ###
