"""Updated Place DTO to have additional details. Updated constraint names to follow a convention

Revision ID: dd7384733110
Revises: 729b72232358
Create Date: 2023-11-15 18:45:47.459632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dd7384733110'
down_revision: Union[str, None] = '729b72232358'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_interests_id', 'interests', type_='unique')
    op.drop_constraint('uq_interests_name', 'interests', type_='unique')
    op.create_unique_constraint('uq__interests__id', 'interests', ['id'])
    op.create_unique_constraint('uq__interests__name', 'interests', ['name'])
    op.drop_constraint('uq_languages_id', 'languages', type_='unique')
    op.drop_constraint('uq_languages_name', 'languages', type_='unique')
    op.create_unique_constraint('uq__languages__id', 'languages', ['id'])
    op.create_unique_constraint('uq__languages__name', 'languages', ['name'])
    op.drop_constraint('uq_occupations_id', 'occupations', type_='unique')
    op.drop_constraint('uq_occupations_name', 'occupations', type_='unique')
    op.create_unique_constraint('uq__occupations__id', 'occupations', ['id'])
    op.create_unique_constraint('uq__occupations__name', 'occupations', ['name'])
    op.add_column('places', sa.Column('google_place_id', sa.String(), nullable=False))
    op.add_column('places', sa.Column('additional_details', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.create_unique_constraint('uq__places__google_place_id', 'places', ['google_place_id'])
    op.drop_constraint('uq_skills_id', 'skills', type_='unique')
    op.drop_constraint('uq_skills_name', 'skills', type_='unique')
    op.create_unique_constraint('uq__skills__id', 'skills', ['id'])
    op.create_unique_constraint('uq__skills__name', 'skills', ['name'])
    op.add_column('user_past_locations', sa.Column('user_preferred_sort_order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_past_locations', 'user_preferred_sort_order')
    op.drop_constraint('uq__skills__name', 'skills', type_='unique')
    op.drop_constraint('uq__skills__id', 'skills', type_='unique')
    op.create_unique_constraint('uq_skills_name', 'skills', ['name'])
    op.create_unique_constraint('uq_skills_id', 'skills', ['id'])
    op.drop_constraint('uq__places__google_place_id', 'places', type_='unique')
    op.drop_column('places', 'additional_details')
    op.drop_column('places', 'google_place_id')
    op.drop_constraint('uq__occupations__name', 'occupations', type_='unique')
    op.drop_constraint('uq__occupations__id', 'occupations', type_='unique')
    op.create_unique_constraint('uq_occupations_name', 'occupations', ['name'])
    op.create_unique_constraint('uq_occupations_id', 'occupations', ['id'])
    op.drop_constraint('uq__languages__name', 'languages', type_='unique')
    op.drop_constraint('uq__languages__id', 'languages', type_='unique')
    op.create_unique_constraint('uq_languages_name', 'languages', ['name'])
    op.create_unique_constraint('uq_languages_id', 'languages', ['id'])
    op.drop_constraint('uq__interests__name', 'interests', type_='unique')
    op.drop_constraint('uq__interests__id', 'interests', type_='unique')
    op.create_unique_constraint('uq_interests_name', 'interests', ['name'])
    op.create_unique_constraint('uq_interests_id', 'interests', ['id'])
    # ### end Alembic commands ###
