from os import getenv
from dotenv import load_dotenv
load_dotenv()

DATABASE_URL = getenv('DATABASE_URL')
KEYCLOAK_URL = getenv('KEYCLOAK_URL')
KEYCLOAK_CLIENT_ID = getenv('KEYCLOAK_CLIENT_ID')
KEYCLOAK_CLIENT_SECRET = getenv('KEYCLOAK_CLIENT_SECRET')
KEYCLOAK_REALM = getenv('KEYCLOAK_REALM')
STREAM_ACCESS_KEY_ID = getenv('STREAM_ACCESS_KEY_ID')
STREAM_SECRET_ACCESS_KEY = getenv('STREAM_SECRET_ACCESS_KEY')
MEDIA_UPLOAD_BUCKET = getenv('MEDIA_UPLOAD_BUCKET')
MEDIA_UPLOAD_URL_VALIDITY = int(getenv('MEDIA_UPLOAD_URL_VALIDITY'))
S3_ENDPOINT="https://s3.me-central-1.amazonaws.com"
AWS_DEFAULT_REGION="me-central-1"
GOOGLE_MAPS_API_KEY = getenv('GOOGLE_MAPS_API_KEY')